kind = "web"
previewPath = "/"
title = "Beast Sensi 7"
version = "1.0.0"
id = "artifacts/beast-sensi-7"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18441

[services.development]
run = "pnpm --filter @workspace/beast-sensi-7 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/beast-sensi-7", "run", "build" ]
publicDir = "artifacts/beast-sensi-7/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18441"
BASE_PATH = "/"
